In [39]:
import numpy as np

№ 1 Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [40]:
a = np.arange(1, 11, 1)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


№ 2 Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [41]:
b = np.zeros((3, 3), dtype=int)
print(b)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


№ 3 Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [42]:
c = np.random.randint(1, 11, size=(5,5))
print(c)

[[ 9  8  7  5  8]
 [ 4 10  2  6  7]
 [ 9  5  4  8  4]
 [ 8 10  7  6  1]
 [ 7  1  6  4  9]]


№ 4 Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [43]:
d = np.random.random((4,4))
print(d)

[[0.08166283 0.06551037 0.33877077 0.96938706]
 [0.1384659  0.26176974 0.87727281 0.71717918]
 [0.20250234 0.02565984 0.65081242 0.99645421]
 [0.11066374 0.92280544 0.39928313 0.68696092]]


№ 5 Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [44]:
e = np.random.randint(1, 11, size=5)
f = np.random.randint(1, 11, size=5)
print(e, f)
print(e + f)
print(e - f)
print(e * f)

[6 5 8 7 5] [1 1 5 6 8]
[ 7  6 13 13 13]
[ 5  4  3  1 -3]
[ 6  5 40 42 40]


№ 6 Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [45]:
g = np.random.randint(1, 11, size=7)
h = np.random.randint(1, 11, size=7)
print(g, h)
print(np.dot(g,h))

[ 7  6  5  6 10  3  3] [7 5 5 3 9 4 1]
227


№ 7 Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [46]:
i = np.random.randint(1, 11, size=(2,2))
j = np.random.randint(1, 11, size=(2,3))
print(i, j)
print(np.dot(i,j))

[[9 7]
 [8 5]] [[ 3 10 10]
 [ 2  1  1]]
[[41 97 97]
 [34 85 85]]


№ 8 Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [47]:
k = np.random.randint(1, 11, size=(3,3))
print(k)
print(np.linalg.inv(k))

[[ 5  4  9]
 [ 8  3  5]
 [ 7  4 10]]
[[-0.32258065  0.12903226  0.22580645]
 [ 1.4516129   0.41935484 -1.51612903]
 [-0.35483871 -0.25806452  0.5483871 ]]


№ 9 Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [49]:
l = np.random.random((4,4))
print(l)
print(l.T)

[[0.56607073 0.05703472 0.56672699 0.2260379 ]
 [0.01507622 0.38619038 0.81024271 0.71100645]
 [0.51672501 0.09345391 0.70372161 0.57602381]
 [0.00662034 0.9967327  0.65687479 0.11556304]]
[[0.56607073 0.01507622 0.51672501 0.00662034]
 [0.05703472 0.38619038 0.09345391 0.9967327 ]
 [0.56672699 0.81024271 0.70372161 0.65687479]
 [0.2260379  0.71100645 0.57602381 0.11556304]]


№ 10 Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [51]:
m = np.random.randint(1, 11, size=(3,4))
n = np.random.randint(1, 11, size=4)
print(m,n)
print(np.dot(m,n))

[[ 4  3  1  3]
 [ 7  7  3  6]
 [10 10  7  5]] [10  6  7  4]
[ 77 157 229]


№ 11 Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [52]:
o = np.random.random((2,3))
p = np.random.random(3)
print(o,p)
print(np.dot(o,p))

[[0.65513171 0.29782938 0.35646306]
 [0.94152579 0.64567036 0.63151688]] [0.51857476 0.1980535  0.31727494]
[0.51181772 0.81649327]


№ 12 Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [54]:
r = np.random.randint(1, 11, size=(2,2))
s = np.random.randint(1, 11, size=(2,2))
print(r, s)
print(r * s)

[[10 10]
 [ 7  2]] [[ 7  2]
 [ 6 10]]
[[70 20]
 [42 20]]


№ 13 Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [56]:
t = np.random.randint(1, 11, size=(2,2))
u = np.random.randint(1, 11, size=(2,2))
print(t, u)
print(np.dot(t, u))

[[3 2]
 [7 7]] [[4 1]
 [3 7]]
[[18 17]
 [49 56]]


№ 14 Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [58]:
v = np.random.randint(1, 101, size=(5,5))
print(v)
print(v.sum())
print(np.sum(v))

[[69  8 11 99 24]
 [ 9 34 28 63  8]
 [10 52 35 60 57]
 [87  9 33 68 62]
 [42 24 49 95 42]]
1078
1078


№ 15 Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [59]:
w = np.random.randint(1, 11, size=(4,4))
x = np.random.randint(1, 11, size=(4,4))
print(w, x)
print(w - x)

[[ 6  3  9  5]
 [ 9  9 10  5]
 [ 3  5  4  9]
 [ 8  2  2  9]] [[10  2  1  3]
 [ 8  8 10  5]
 [ 5  7  6 10]
 [ 7  9  8  4]]
[[-4  1  8  2]
 [ 1  1  0  0]
 [-2 -2 -2 -1]
 [ 1 -7 -6  5]]


№ 16 Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [63]:
y = np.random.random((3,3))
print(y)
sum = np.sum(y, axis=1)
print(sum.reshape(-1,1))

[[0.37912612 0.49765098 0.40016689]
 [0.25402282 0.59385381 0.75028157]
 [0.07714158 0.69746415 0.86264686]]
[[1.27694398]
 [1.5981582 ]
 [1.6372526 ]]


№ 17 Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [68]:
z = np.random.randint(1,11, size=(3,4))
print(z)
print(z * z)
print(np.square(z))

[[9 4 4 1]
 [3 8 8 1]
 [2 6 4 9]]
[[81 16 16  1]
 [ 9 64 64  1]
 [ 4 36 16 81]]
[[81 16 16  1]
 [ 9 64 64  1]
 [ 4 36 16 81]]


№ 18 Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [70]:
ab = np.random.randint(1, 51, size=4)
print(ab)
print(np.sqrt(ab))

[12 19  9 46]
[3.46410162 4.35889894 3.         6.78232998]
